name: yummy_wookie
description: Marcato Hackathon Entry
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  polymer: 1.0.0-rc.7
  web_components: ^0.12.0
  reflectable: ^0.3.0
  polymer_elements: 1.0.0-rc.3
  browser: ^0.10.0
transformers:
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.dart